/planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      downsample_costmap: false           # whether or not to downsample the map
      downsampling_factor: 1              # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      allow_unknown: false                 # allow traveling in unknown space
      max_iterations: -1             # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      max_planning_time: 500.0              # max time in s for planner to plan, smooth
      motion_model_for_search: "DUBIN"    # Hybrid-A* Dubin, Redds-Shepp
      angle_quantization_bins: 120         # Number of angle bins for search
      analytic_expansion_ratio: 3.5       # The ratio to attempt analytic expansions during search for final approach.
      analytic_expansion_max_length: 25.0  # For Hybrid/Lattice nodes: The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting
      minimum_turning_radius: 0.9       # minimum turning radius in m of path / (global costmap resolution * downsampling factor) --> This division doesn't seem to occur when set dynamically.
      reverse_penalty: 2.0                # Penalty to apply if motion is reversing, must be => 1
      change_penalty: 7.0                 # Penalty to apply if motion is changing directions (L to R), must be >= 0
      non_straight_penalty: 0.9           # Penalty to apply if motion is non-straight, must be => 1
      cost_penalty: 15.0                   # Penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
      retrospective_penalty: 0.0
      lookup_table_size: 51.0             # Size of the dubin/reeds-sheep distance window to cache, in meters.
      cache_obstacle_heuristic: false     # Cache the obstacle map dynamic programming distance expansion heuristic between subsiquent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
      smooth_path: false                   # If true, does a simple and quick smoothing post-processing to the path
      tolerance: 1.0
      smoother:
        do_refinement: false
        max_iterations: 1000
        tolerance: 0.5
        w_data: 0.05
        w_smooth: 0.7

global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: map
      robot_base_frame: base_link

      update_frequency: 1.0
      publish_frequency: 1.0

      track_unknown_space: false
      always_send_full_costmap: true
      robot_radius: 1.5

      plugins: ["static_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        subscribe_to_updates: false
        enabled: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 5.0
        cost_scaling_factor: 0.5
        enabled: true
      